language: python

# command to run tests
script: nosetests

notifications:

  email:
    recipients:
      - saintclair@onecloudportal.com.br
      - saintclair.com@gmail.com
    on_success: [change]
    on_failure: [always]

  slack:
      rooms:
        - onecloud:wkytMZEkW53F9Gxn2LPmfugQ#dev-ci
      on_success: [never]
      on_failure: [always]
      on_start: [always]
