language: python

# command to run tests
script: nosetests

notifications:

  email:
    - saintclair@onecloudportal.com.br
  slack:
      rooms:
        - onecloud:wkytMZEkW53F9Gxn2LPmfugQ
      on_success: [never]
      on_failure: [always]
      on_start: [always]
